### ISSUE TITLE
Quiet period calculator cannot be changed

### ISSUE THREAD

**Issue by dmartell-bp** [jenkinsci/tikal-multijob-plugin#200]
The Quiet period calculator has a default of "index < 5 ? 0 : 2 * 60" but cannot be changed.  This is a major bug for anyone trying to spin up more than 4 simultaneous test environments using the MultiJob plugin.

**Comment by caseyduquettesc** [comment]
Luckily, looking at the code, this looks more like a UI bug. You can confirm if you look at your job config history, it saves the values you enter, but when edit the job, it always loads the default value. This unfortunately means you will need to be careful whenever you save the job to always enter a sane value. 

Personally, I'll probably go back to 1.32.

**Comment by xUrko** [comment]
I am still running 1.31 since 1.32 also did not work properly.

**Comment by RochaStratovan** [comment]
Why is the default value anything other than 0. We've had sizable performance hits due to this default value being applied because of some trivial unrelated edit to the job description. It may be caused by a UI issue, but it's a rather serious issue since it silently changes unrelated values.

**Comment by flocsy** [comment]
I agree, please set the default value to be 0, that's backwards compatible with how it behaved before the quietPeriodCalculator was added.

**Comment by RochaStratovan** [comment]
Any idea on when this critical defect will be fixed?

**Comment by srilakalways** [comment]
> I agree, please set the default value to be 0, that's backwards compatible with how it behaved before the quietPeriodCalculator was added.

Where can the value be changed globally?

**Comment by anoymouserver** [comment]
should be fixed with #201

**Comment by RochaStratovan** [comment]
Do we know when this will be _released?_ I have latest 1.33 and I still see this issue.

**Comment by ccnet-microarea** [comment]
> Do we know when this will be _released?_ I have latest 1.33 and I still see this issue.

Me too! That's the reason because i don't upgrade from 1.32, _**but**_ 1.32 has the [Next phase is EXECUTING even though the previous phase is FAILED](https://github.com/jenkinsci/tikal-multijob-plugin/issues/189) issue, which is pretty critical for us...

**Comment by naqushab** [comment]
Any update on the fix? Is there a workaround to this?

**Comment by yorammi** [comment]
We released 1.36 (at last - we have odd authentication issues with jenkins-CI) and it includes a fix for this issue.
